### ISSUE TITLE
Interpreter: CoSimulation Test always fails on Linux

### ISSUE THREAD

**Issue by ldcouto** [symphonytool/symphony#271] opened 2014-07-01 11:15 UTC
eu.compassresearch.core.interpreter.CoSimulationIntegrationTest

No matter what we try, it always fails on Linux. It fails sometimes on Windows. Mac failures unknown.

On Linux, the test runs for a long time and then fails with: `java.lang.AssertionError: Simulators did not finish successfully`.

**Comment by joey-coleman** [comment] 2014-07-02 12:57
I'm fairly sure it passes on my mac 99% of the time; most of time I build I am not skipping the tests (and I last build around noon on 2 July, commit cc85799).

**Comment by ldcouto** [comment] 2014-07-02 14:51
I don't know too much about how the interpreter does parallelisms but if it's calling on the OS to spawn processes, that might explain why we have such different outcomes.

@lausdahl , do you know how (or at least where in the code) parallelism are simulated?

**Comment by lausdahl** [comment] 2014-07-06 21:50
"parallelisms" how did that come into the discussion?

co-sim is distributed simulation, and thus multiple processes. Each process represents one distributed simulated process.

This issue has nothing to do with how the process is defined.

The issue is how the external processes are controller, mainly how their terminal output is captured.

**Comment by ldcouto** [comment] 2014-07-07 09:04
You're right. Though I seem to remember some kind of "did not deadlock" error. Maybe that's what got me thinking parallelism.

If the external processes are managed by the OS, then that is our likely culprit.

**Comment by joey-coleman** [comment] 2014-07-29 10:19
Fixed by at least 5e548c4 (and possibly fixed in Kenneth's e8cd77e)

**Closed as completed by joey-coleman** 2014-07-29 10:19 UTC
Labels: bug
